language: python
matrix:
  include:
    - name: "Python 2.7 on Ubuntu 16.04"
      os: precise
      python: 2.7
      script:
        - python -m request_generator.html.dom.tests.simple_html_element
        - python -m request_generator.html.tests.html_request_builder
        - python -m request_generator.html.jquery.tests.jquery_request_builder        
    - name: "Python 2.7 on OSX"
      os: osx
      language: shell
      install:
        - pip install six
        - pip install future
      script:
        - python -m request_generator.html.dom.tests.simple_html_element
        - python -m request_generator.html.tests.html_request_builder
        - python -m request_generator.html.jquery.tests.jquery_request_builder
    - name: "Jython on OSX"
      os: osx
      language: shell
      jdk:
        - oraclejdk6
      before_install:
        - mkdir ~/Downloads/Jython
        - wget -O ~/Downloads/Jython/jython.jar https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar
        - chmod +x .travis/run-jython-tests.sh
      script:
        "./.travis/run-jython-tests.sh"